language: node_js
node_js: '8'

cache:
  yarn: true
  directories:
    - node_modules


install:
  - yarn --frozen-lockfile --non-interactive
  - yarn run build
before_deploy: "echo 'ready?'"
deploy:
  local_dir: docs
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
