language: node_js
node_js: '8'

cache:
  yarn: true
  directories:
    - node_modules

before_install:


install:
  - yarn --frozen-lockfile --non-interactive

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
